app:
  host: localhost
  port: 9717
srs:
  mode: edge
  domain: 172.31.103.161
  rtmpPort: 8935
  host: 172.31.103.161
  httpPort: 8985
nacos:
  servers:
    - host: 172.31.103.161
      port: 18848
  namespaceId: public
  groupName: public
  auth: false
