[app]
# 需要配置到 Prometheus 的当前服务的 Host
host = "localhost"
port = 9717

[srs]
# 区分 SRS 的源站和边缘站
mode = "edge"
# domain + rtmp_port (external service)
domain = "localhost"
rtmp_port = 1935
# host + http_port (internal service)
host = "localhost"
http_port = 1985

[nacos]

host = "172.31.103.161"
port = 18848
namespace_id = "public"
group_name = "public"
# 默认不开启认证
auth = false
# 可选的用户名密码
username = "nacos"
password = "nacos"