[app]
port = 9717
host = "localhost"

[srs]
host = "localhost"
mode = "origin"
rtmp_port = 1935
http_port = 1985

[nacos]
host = "localhost"
port = 8848
namespace_id = "public"
group_name = "DEFAULT_GROUP"
